name: Deploy Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do repositório
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Publica diretamente as suas páginas estáticas no GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: src/main/resources/static # Aponta direto para a pasta do seu site!
        branch: gh-pages